(function(){
var $=function(id){return document.getElementById(id)};var PERMS=null;
function hideAll(){['hub','items','contactInbox','financePanel','sheetPanel','permissionsPanel','bannerPanel'].forEach(function(id){var e=$(id);if(e)e.classList.add('hidden')});var n=$('newItem');if(n)n.classList.add('hidden')}
function session(){try{var s=JSON.parse(sessionStorage.getItem('riu_session')||'null');var h=JSON.parse(localStorage.getItem('riu_hub_session')||'null');if(s&&s.token)return {token:s.token,uid:s.uid,role:s.role||(h&&h.uid===s.uid?h.role:null)};return h}catch(e){return null}}
function auth(){var s=session();return s&&s.token?s:null}
async function req(path,opt){var s=auth();if(!s)throw Error('Please sign in again.');opt=opt||{};var headers=Object.assign({'apikey':'sb_publishable_J8u9PnOnfhnUhT1ORgfrgw_TMkTo7J5','Authorization':'Bearer '+s.token,'Content-Type':'application/json'},opt.headers||{});var r=await fetch('https://uowznuvauqfgeewtqgwo.supabase.co'+path,Object.assign({},opt,{headers:headers}));if(!r.ok)throw Error(await r.text());var t=await r.text();return t?JSON.parse(t):[]}
async function capture(){var ss=JSON.parse(sessionStorage.getItem('riu_session')||'null');var token=ss&&ss.token?ss.token:'';if(!token||!ss||!ss.uid)return null;var r=await fetch('https://uowznuvauqfgeewtqgwo.supabase.co/rest/v1/staff_profiles?id=eq.'+encodeURIComponent(ss.uid)+'&select=id,role,active',{headers:{apikey:'sb_publishable_J8u9PnOnfhnUhT1ORgfrgw_TMkTo7J5',Authorization:'Bearer '+token}});if(!r.ok)return null;var p=await r.json(),mine=p[0];if(!mine||!mine.active)return null;var s={token:token,uid:mine.id,role:mine.role};sessionStorage.setItem('riu_session',JSON.stringify(s));localStorage.setItem('riu_hub_session',JSON.stringify(s));return s}
function safe(x){var d=document.createElement('div');d.textContent=x==null?'':String(x);return d.innerHTML}
async function hub(){hideAll();$('hub').classList.remove('hidden');$('viewTitle').textContent='LABEL HUB';try{
var data=await Promise.all([
req('/rest/v1/staff_profiles?active=eq.true&select=id,role'),
req('/rest/v1/content_items?content_type=eq.artist&select=id,title,subtitle,image_url,status&order=sort_order.asc,updated_at.desc'),
req('/rest/v1/content_items?content_type=eq.event&status=eq.published&select=id,title,event_date,event_end,location,venue,image_url,event_type&order=event_date.asc&limit=6'),
req('/rest/v1/label_finance_summary?select=*'),
req('/rest/v1/staff_presence?select=user_id,last_seen'),
req('/rest/v1/artist_management?select=*')
]);
var profiles=data[0],artists=data[1],events=data[2],fin=data[3][0]||{},presence=data[4],management=data[5],s=auth(),canBank=s.role==='owner'||!!(PERMS&&PERMS.view_bank),canManage=s.role==='owner'||!!(PERMS&&PERMS.manage_artists);
var online=presence.filter(function(x){return Date.now()-new Date(x.last_seen).getTime()<300000}).map(function(x){var p=profiles.find(function(y){return y.id===x.user_id});return p?{role:p.role,last_seen:x.last_seen}:null}).filter(Boolean);
var needs=management.filter(function(x){return x.management_status==='needs_attention'}).length,inactive=management.filter(function(x){return x.management_status==='inactive'}).length;
var bank=canBank?'$'+Number(fin.current_balance||0).toLocaleString():'HIDDEN';
var roster=artists.map(function(a){var m=management.find(function(x){return x.artist_id===a.id})||{management_status:'active',artist_revenue_split:60,label_revenue_split:40};var img=a.image_url?'<img src="'+safe(a.image_url)+'" alt="">':'<div class="artist-fallback">'+safe((a.title||'?').slice(0,1))+'</div>';return '<article class="hub-artist-card" data-artist="'+a.id+'"><div class="hub-artist-photo">'+img+'<span class="artist-status '+m.management_status+'">'+m.management_status.replace('_',' ').toUpperCase()+'</span></div><div class="hub-artist-info"><small>SIGNED ARTIST</small><h3>'+safe(a.title)+'</h3><p>'+safe(a.subtitle||'Run It Up Records')+'</p><div class="split-line"><span>ARTIST <b>'+Number(m.artist_revenue_split||0)+'%</b></span><span>LABEL <b>'+Number(m.label_revenue_split||0)+'%</b></span></div>'+(m.last_checkin?'<div class="checkin">LAST CHECK-IN · '+new Date(m.last_checkin).toLocaleDateString()+'</div>':'<div class="checkin attention">NO CHECK-IN LOGGED</div>')+(canManage?'<button class="manage-artist" data-manage="'+a.id+'">MANAGE ARTIST</button>':'')+'</div></article>'}).join('');
var ev=events.length?events.map(function(x){return '<article class="hub-event-card">'+(x.image_url?'<img src="'+safe(x.image_url)+'" alt="">':'')+'<div><small>'+safe(x.event_type||'UPCOMING EVENT')+'</small><h3>'+safe(x.title)+'</h3><p>'+(x.event_date?new Date(x.event_date).toLocaleString():'TBA')+'</p><span>'+safe(x.venue||x.location||'Location TBA')+'</span></div></article>'}).join(''):'<p class="hub-empty">No upcoming events scheduled.</p>';
$('hub').innerHTML='<section class="hub-hero-grid"><article class="bank-hero '+(canBank?'':'bank-hidden')+'"><small>RUN IT UP RECORDS · LABEL BANK</small><div class="bank-number">'+bank+'</div><p>'+(canBank?'LIVE TRACKED BALANCE':'BALANCE VISIBILITY DISABLED BY OWNER')+'</p></article><article class="hub-pulse"><small>LABEL PULSE</small><div><b>'+artists.length+'</b><span>ARTISTS</span></div><div><b>'+needs+'</b><span>NEED ATTENTION</span></div><div><b>'+inactive+'</b><span>INACTIVE</span></div></article></section><section class="hub-section"><div class="hub-section-head"><div><small>WHO IS HERE</small><h2>ACTIVE STAFF</h2></div><span>'+online.length+' ONLINE</span></div><div class="active-staff-list">'+(online.length?online.map(function(o){return '<div class="staff-chip"><i></i><div><b>'+o.role.replaceAll('_',' ').toUpperCase()+'</b><small>ACTIVE NOW</small></div></div>'}).join(''):'<p class="hub-empty">No other active staff detected.</p>')+'</div></section><section class="hub-section"><div class="hub-section-head"><div><small>ARTIST MANAGEMENT</small><h2>LABEL ROSTER</h2></div><span>'+artists.length+' SIGNED</span></div><div class="hub-artist-grid">'+roster+'</div></section><section class="hub-section"><div class="hub-section-head"><div><small>CALENDAR</small><h2>UPCOMING EVENTS</h2></div></div><div class="hub-event-grid">'+ev+'</div></section>';
document.querySelectorAll('[data-manage]').forEach(function(b){b.onclick=function(){openArtistManager(b.dataset.manage,artists,management)}});
await req('/rest/v1/staff_presence?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:s.uid,last_seen:new Date().toISOString()})})
}catch(e){$('hub').innerHTML='<p>'+safe(e.message)+'</p>'}}
function openArtistManager(id,artists,management){var a=artists.find(function(x){return x.id===id}),m=management.find(function(x){return x.artist_id===id})||{management_status:'active',artist_revenue_split:60,label_revenue_split:40,notes:''};var modal=document.createElement('div');modal.className='hub-modal';modal.innerHTML='<div class="hub-modal-card"><button class="hub-modal-x">×</button><small>ARTIST MANAGEMENT</small><h2>'+safe(a?a.title:'ARTIST')+'</h2><label>STATUS<select id="amStatus"><option value="active">ACTIVE</option><option value="inactive">INACTIVE</option><option value="needs_attention">NEEDS ATTENTION</option></select></label><div class="split-editor"><label>ARTIST SPLIT %<input id="amArtist" type="number" min="0" max="100" step=".01" value="'+Number(m.artist_revenue_split||60)+'"></label><label>LABEL SPLIT %<input id="amLabel" type="number" min="0" max="100" step=".01" value="'+Number(m.label_revenue_split||40)+'"></label></div><label>NEXT RELEASE<input id="amRelease" value="'+safe(m.next_release||'')+'" placeholder="Single / EP / project name"></label><label>NEXT RELEASE DATE<input id="amReleaseDate" type="datetime-local" value="'+(m.next_release_date?new Date(m.next_release_date).toISOString().slice(0,16):'')+'"></label><label>MANAGEMENT NOTES<textarea id="amNotes">'+safe(m.notes||'')+'</textarea></label><button id="amSave">SAVE ARTIST MANAGEMENT</button></div>';document.body.appendChild(modal);modal.querySelector('#amStatus').value=m.management_status||'active';modal.querySelector('.hub-modal-x').onclick=function(){modal.remove()};modal.querySelector('#amSave').onclick=async function(){var ar=Number(modal.querySelector('#amArtist').value),lr=Number(modal.querySelector('#amLabel').value);if(Math.abs(ar+lr-100)>.001){alert('Artist and label revenue splits must equal 100%.');return}await req('/rest/v1/artist_management?on_conflict=artist_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({artist_id:id,management_status:modal.querySelector('#amStatus').value,artist_revenue_split:ar,label_revenue_split:lr,notes:modal.querySelector('#amNotes').value,next_release:modal.querySelector('#amRelease').value,next_release_date:modal.querySelector('#amReleaseDate').value?new Date(modal.querySelector('#amReleaseDate').value).toISOString():null,last_checkin:new Date().toISOString(),updated_at:new Date().toISOString(),updated_by:auth().uid})});modal.remove();hub()}}
async function finance(){hideAll();$('financePanel').classList.remove('hidden');$('viewTitle').textContent='LABEL FINANCES';try{var a=await Promise.all([req('/rest/v1/label_finance_summary?select=*'),req('/rest/v1/financial_transactions?select=*&order=created_at.desc&limit=100')]),s=a[0][0]||{};$('financePanel').innerHTML='<div class="metric-grid"><article class="metric money"><span>CURRENT BANK</span><strong>$'+Number(s.current_balance||0).toLocaleString()+'</strong></article><article class="metric"><span>MONEY IN</span><strong>$'+Number(s.total_in||0).toLocaleString()+'</strong></article><article class="metric"><span>MONEY OUT</span><strong>$'+Number(s.total_out||0).toLocaleString()+'</strong></article></div><form id="hubTx" class="finance-form"><select id="hubDir"><option value="in">MONEY IN</option><option value="out">MONEY OUT</option></select><input id="hubAmt" type="number" min="0" step=".01" placeholder="Amount" required><input id="hubCat" placeholder="Category"><input id="hubMemo" placeholder="Reason"><button>POST TRANSACTION</button></form><div class="ledger">'+a[1].map(function(x){return '<div class="ledger-row '+x.direction+'"><b>'+(x.direction==='in'?'+':'-')+'$'+Number(x.amount).toLocaleString()+'</b><span>'+safe(x.category||'General')+'</span><span>'+safe(x.memo||'')+'</span><small>'+new Date(x.created_at).toLocaleString()+'</small></div>'}).join('')+'</div>';$('hubTx').onsubmit=async function(e){e.preventDefault();await req('/rest/v1/financial_transactions',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({direction:$('hubDir').value,amount:Number($('hubAmt').value),category:$('hubCat').value,memo:$('hubMemo').value,created_by:auth().uid})});finance()}}catch(e){$('financePanel').innerHTML='<p>'+safe(e.message)+'</p>'}}
async function sheet(){hideAll();$('sheetPanel').classList.remove('hidden');$('viewTitle').textContent='FINANCE WORKBOOK';if(window.RIUSpreadsheet){await window.RIUSpreadsheet.open();return}try{var sh=(await req('/rest/v1/finance_sheets?select=*'))[0],rows=await req('/rest/v1/finance_cells?sheet_id=eq.'+sh.id+'&select=*'),vals={};rows.forEach(function(x){vals[x.cell_ref]=x.raw_value||''});var html='<div class="sheet-toolbar"><b>'+safe(sh.name)+'</b><span>Autosaves every changed cell</span></div><div id="hubGrid" class="sheet-grid"><div class="corner"></div>';for(var c=1;c<=12;c++)html+='<div class="col-head">'+String.fromCharCode(64+c)+'</div>';for(var r=1;r<=40;r++){html+='<div class="row-head">'+r+'</div>';for(var c2=1;c2<=12;c2++){var ref=String.fromCharCode(64+c2)+r;html+='<input class="sheet-cell" data-ref="'+ref+'" value="'+safe(vals[ref]||'')+'">'}}html+='</div>';$('sheetPanel').innerHTML=html;document.querySelectorAll('#hubGrid .sheet-cell').forEach(function(i){i.onchange=async function(){await req('/rest/v1/finance_cells?on_conflict=sheet_id,cell_ref',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({sheet_id:sh.id,cell_ref:i.dataset.ref,raw_value:i.value,updated_by:auth().uid})})}})}catch(e){$('sheetPanel').innerHTML='<p>'+safe(e.message)+'</p>'}}
async function perms(){var s=auth();if(!s||s.role!=='owner'){hub();return}hideAll();$('permissionsPanel').classList.remove('hidden');$('viewTitle').textContent='ROLE PERMISSIONS';try{var rows=await req('/rest/v1/role_permissions?select=*&order=role.asc'),keys=[['artists','ARTISTS'],['music','MUSIC'],['events','EVENTS'],['gallery','GALLERY'],['team','TEAM'],['inbox','CONTACT INBOX'],['finance','FINANCES'],['spreadsheet','SPREADSHEET'],['view_bank','VIEW LABEL BANK'],['manage_artists','MANAGE ARTISTS'],['banner','HOMEPAGE BANNER']];$('permissionsPanel').innerHTML='<div class="permission-intro"><small>OWNER CONTROL</small><h2>STAFF ACCESS</h2><p>Dashboard Hub is always available to every staff role. Check which systems each role can access.</p></div>'+rows.map(function(r){return '<section class="permission-card"><h2>'+r.role.replaceAll('_',' ').toUpperCase()+'</h2><label class="hub-required"><input type="checkbox" checked disabled>DASHBOARD HUB <small>REQUIRED</small></label>'+keys.map(function(k){return '<label><input type="checkbox" data-role="'+r.role+'" data-key="'+k[0]+'" '+((r.role==='owner'||r.permissions[k[0]])?'checked':'')+' '+(r.role==='owner'?'disabled':'')+'>'+k[1]+'</label>'}).join('')+'</section>'}).join('');document.querySelectorAll('#permissionsPanel input[data-role]:not(:disabled)').forEach(function(i){i.onchange=async function(){var row=rows.find(function(x){return x.role===i.dataset.role});row.permissions[i.dataset.key]=i.checked;await req('/rest/v1/role_permissions?role=eq.'+i.dataset.role,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({permissions:row.permissions,updated_by:auth().uid})});await applyPermissions()}})}catch(e){$('permissionsPanel').innerHTML='<p>'+safe(e.message)+'</p>'}}
async function applyPermissions(){var s=auth();if(!s)return;var rows=await req('/rest/v1/role_permissions?role=eq.'+encodeURIComponent(s.role)+'&select=permissions'),p=s.role==='owner'?{artists:true,music:true,events:true,gallery:true,team:true,inbox:true,finance:true,spreadsheet:true,view_bank:true,manage_artists:true,banner:true}:(rows[0]&&rows[0].permissions||{});PERMS=p;document.querySelectorAll('[data-permission]').forEach(function(b){b.classList.toggle('hidden',!p[b.dataset.permission])});$('permissionsBtn').classList.toggle('hidden',s.role!=='owner');$('hubBtn').classList.remove('hidden');return p}
function allowed(key){return auth()&&auth().role==='owner'||!!(PERMS&&PERMS[key])}
async function wire(){var s=await capture();if(!s)return;await applyPermissions();$('hubBtn').onclick=hub;$('financeBtn').onclick=function(){if(allowed('finance'))finance();else hub()};$('sheetBtn').onclick=function(){if(allowed('spreadsheet'))sheet();else hub()};$('permissionsBtn').onclick=perms;document.querySelectorAll('[data-view]').forEach(function(b){b.addEventListener('click',function(e){var map={artist:'artists',release:'music',event:'events',gallery:'gallery',team:'team'},k=map[b.dataset.view];if(!allowed(k)){e.preventDefault();e.stopImmediatePropagation();hub()}},true)});$('inboxBtn').addEventListener('click',function(e){if(!allowed('inbox')){e.preventDefault();e.stopImmediatePropagation();hub()}},true);hub()}
var obs=new MutationObserver(function(){if(!$('dashboard').classList.contains('hidden'))wire()});obs.observe($('dashboard'),{attributes:true,attributeFilter:['class']});if(!$('dashboard').classList.contains('hidden'))wire();
})();