(function(){
const SB='https://uowznuvauqfgeewtqgwo.supabase.co',KEY='sb_publishable_J8u9PnOnfhnUhT1ORgfrgw_TMkTo7J5';
let book=null,row=null,active='sheet1',selected={r:0,c:0},anchor=null,history=[],future=[],saveTimer=null,editing=false,rt=null,channel=null;
const $=id=>document.getElementById(id), letters=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s},ref=(r,c)=>letters(c)+(r+1);
function session(){try{return JSON.parse(sessionStorage.getItem('riu_session')||'null')}catch{return null}}
async function api(path,opt={}){let s=session();if(!s)throw Error('Sign in again');let r=await fetch(SB+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+s.token,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());let t=await r.text();return t?JSON.parse(t):[]}
function fresh(){return {version:1,active:'sheet1',sheets:[{id:'sheet1',name:'Label Finance',rows:200,cols:26,cells:{A1:{v:'RUN IT UP RECORDS — FINANCE',b:1},A3:{v:'Date',b:1},B3:{v:'Category',b:1},C3:{v:'Description',b:1},D3:{v:'Money In',b:1},E3:{v:'Money Out',b:1},F3:{v:'Balance',b:1}},widths:{},heights:{},freeze:{r:3,c:0}}]}}
const sheet=()=>book.sheets.find(s=>s.id===active)||book.sheets[0], cell=(r,c,make=true)=>{let s=sheet(),k=ref(r,c);if(!s.cells[k]&&make)s.cells[k]={v:''};return s.cells[k]||{v:''}};
function snap(){history.push(JSON.stringify(book));if(history.length>60)history.shift();future=[]}
function restore(x){book=JSON.parse(x);active=book.active||book.sheets[0].id;renderAll();queueSave()}
function val(r,c,stack=[]){let x=cell(r,c,false).v??'';if(typeof x!=='string'||x[0]!=='=')return x;let key=ref(r,c);if(stack.includes(key))return '#CYCLE!';try{return formula(x.slice(1),stack.concat(key))}catch{return '#ERROR!'}}
function formula(f,stack){let s=f.trim(),range=(a,b)=>{let A=parse(a),B=parse(b),out=[];for(let r=A.r;r<=B.r;r++)for(let c=A.c;c<=B.c;c++)out.push(Number(val(r,c,stack))||0);return out},repl=s.replace(/(SUM|AVERAGE|MIN|MAX|COUNT)\(([A-Z]+\d+):([A-Z]+\d+)\)/gi,(m,fn,a,b)=>{let x=range(a,b);return fn.toUpperCase()==='SUM'?x.reduce((p,q)=>p+q,0):fn.toUpperCase()==='AVERAGE'?(x.reduce((p,q)=>p+q,0)/(x.length||1)):fn.toUpperCase()==='MIN'?Math.min(...x):fn.toUpperCase()==='MAX'?Math.max(...x):x.length}).replace(/([A-Z]+\d+)/g,m=>JSON.stringify(val(parse(m).r,parse(m).c,stack)));if(!/^[0-9eE+\-*/()., "'<>=!&]+$/.test(repl))throw Error();return Function('"use strict";return ('+repl+')')()}
function parse(a){let m=/^([A-Z]+)(\d+)$/i.exec(a),c=0;for(let ch of m[1].toUpperCase())c=c*26+ch.charCodeAt(0)-64;return {r:+m[2]-1,c:c-1}}
function renderGrid(){let s=sheet(),g=$('nativeGrid'),html='<div class="ns-corner"></div>';for(let c=0;c<s.cols;c++)html+='<div class="ns-col" data-c="'+c+'">'+letters(c)+'</div>';for(let r=0;r<s.rows;r++){html+='<div class="ns-row" data-r="'+r+'">'+(r+1)+'</div>';for(let c=0;c<s.cols;c++){let x=cell(r,c,false),style='';if(x.bg)style+='background:'+x.bg+';';if(x.color)style+='color:'+x.color+';';if(x.align)style+='text-align:'+x.align+';';if(x.b)style+='font-weight:800;';if(x.i)style+='font-style:italic;';if(x.u)style+='text-decoration:underline;';html+='<div class="ns-cell '+(r===selected.r&&c===selected.c?'selected':'')+'" data-r="'+r+'" data-c="'+c+'" style="'+style+'">'+escape(String(val(r,c)))+'</div>'}}g.innerHTML=html;g.style.gridTemplateColumns='46px repeat('+s.cols+',100px)';bindCells()}
function escape(v){let d=document.createElement('div');d.textContent=v;return d.innerHTML}
function bindCells(){document.querySelectorAll('.ns-cell').forEach(e=>{e.onmousedown=x=>{selected={r:+e.dataset.r,c:+e.dataset.c};anchor=selected;showSelection();setTimeout(beginEdit,0)}});$('nativeGrid').onkeydown=keys}
function showSelection(){document.querySelectorAll('.ns-cell.selected').forEach(e=>e.classList.remove('selected'));let e=document.querySelector('.ns-cell[data-r="'+selected.r+'"][data-c="'+selected.c+'"]');if(e){e.classList.add('selected');e.scrollIntoView({block:'nearest',inline:'nearest'})}$('nameBox').value=ref(selected.r,selected.c);$('formulaInput').value=cell(selected.r,selected.c,false).v??''}
function beginEdit(){if(editing)return;let e=document.querySelector('.ns-cell[data-r="'+selected.r+'"][data-c="'+selected.c+'"]');if(!e)return;editing=true;let raw=cell(selected.r,selected.c,false).v??'';e.innerHTML='<input class="ns-editor">';let i=e.firstChild;i.value=raw;i.focus();i.select();i.onblur=()=>commit(i.value);i.onkeydown=x=>{if(x.key==='Enter'){x.preventDefault();let nr=Math.min(sheet().rows-1,selected.r+1);i.blur();selected.r=nr;setTimeout(()=>{showSelection();beginEdit()},0)}if(x.key==='Tab'){x.preventDefault();let nc=Math.min(sheet().cols-1,selected.c+(x.shiftKey?-1:1));i.blur();selected.c=Math.max(0,nc);setTimeout(()=>{showSelection();beginEdit()},0)}if(x.key==='Escape'){editing=false;renderGrid();showSelection()}}}
function commit(v){snap();let rr=selected.r,cc=selected.c;cell(rr,cc).v=v;editing=false;renderGrid();showSelection();saveCell(rr,cc);queueSave()}
function keys(e){if(editing)return;if(e.key==='Enter'||e.key==='F2'){e.preventDefault();beginEdit();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}let d={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]}[e.key];if(d){e.preventDefault();selected.r=Math.max(0,Math.min(sheet().rows-1,selected.r+d[0]));selected.c=Math.max(0,Math.min(sheet().cols-1,selected.c+d[1]));showSelection()}if(e.key==='Delete'){snap();cell(selected.r,selected.c).v='';renderGrid();queueSave()}}
function format(k,v){snap();let x=cell(selected.r,selected.c);x[k]=v===undefined?!x[k]:v;renderGrid();saveCell(selected.r,selected.c);queueSave()}
function undo(){if(!history.length)return;future.push(JSON.stringify(book));restore(history.pop())}function redo(){if(!future.length)return;history.push(JSON.stringify(book));restore(future.pop())}
function tabs(){let x=$('sheetTabs');x.innerHTML=book.sheets.map(s=>'<button class="'+(s.id===active?'active':'')+'" data-sheet="'+s.id+'">'+escape(s.name)+'</button>').join('')+'<button id="addSheet">＋</button>';x.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>{active=b.dataset.sheet;book.active=active;renderAll();queueSave()});$('addSheet').onclick=()=>{snap();let id='sheet'+Date.now();book.sheets.push({id,name:'Sheet '+(book.sheets.length+1),rows:200,cols:26,cells:{},widths:{},heights:{},freeze:{r:0,c:0}});active=id;book.active=id;renderAll();queueSave()}}
function renderAll(){tabs();renderGrid();showSelection()}
async function load(){let a=await api('/rest/v1/finance_workbooks?select=*&order=created_at.asc&limit=1');row=a[0];book=row&&row.snapshot&&row.snapshot.sheets?row.snapshot:fresh();active=book.active||book.sheets[0].id;await loadLiveCells();await startRealtime()}
async function saveCell(r,c){if(!row)return;let x=cell(r,c,false),s=session();$('sheetSaveState').textContent='SAVING LIVE';try{await api('/rest/v1/finance_realtime_cells?on_conflict=workbook_id,sheet_id,cell_ref',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({workbook_id:row.id,sheet_id:active,cell_ref:ref(r,c),raw_value:String(x.v??''),formatting:{b:x.b||0,i:x.i||0,u:x.u||0,align:x.align||null,color:x.color||null,bg:x.bg||null},updated_by:s.uid,updated_at:new Date().toISOString()})});$('sheetSaveState').textContent='LIVE · SAVED'}catch(e){$('sheetSaveState').textContent='LIVE SAVE ERROR'}}
async function loadLiveCells(){if(!row)return;let rows=await api('/rest/v1/finance_realtime_cells?workbook_id=eq.'+row.id+'&select=*');rows.forEach(applyRemote)}
function applyRemote(x){let sh=book&&book.sheets&&book.sheets.find(q=>q.id===x.sheet_id);if(!sh)return;let v=sh.cells[x.cell_ref]||(sh.cells[x.cell_ref]={v:''});v.v=x.raw_value;Object.assign(v,x.formatting||{});if(x.sheet_id===active&&!editing){let p=parse(x.cell_ref);if(p.r===selected.r&&p.c===selected.c)$('formulaInput').value=v.v;let e=document.querySelector('.ns-cell[data-r="'+p.r+'"][data-c="'+p.c+'"]');if(e){e.textContent=String(val(p.r,p.c));let st='';if(v.bg)st+='background:'+v.bg+';';if(v.color)st+='color:'+v.color+';';if(v.align)st+='text-align:'+v.align+';';if(v.b)st+='font-weight:800;';if(v.i)st+='font-style:italic;';if(v.u)st+='text-decoration:underline;';e.style.cssText=st}}}
async function startRealtime(){if(!window.supabase||!row)return;let s=session();rt=window.supabase.createClient(SB,KEY,{auth:{persistSession:false,autoRefreshToken:false}});await rt.realtime.setAuth(s.token);if(channel)await rt.removeChannel(channel);channel=rt.channel('riu-workbook-'+row.id).on('postgres_changes',{event:'*',schema:'public',table:'finance_realtime_cells',filter:'workbook_id=eq.'+row.id},payload=>{let x=payload.new;if(!x||x.updated_by===s.uid)return;applyRemote(x);$('sheetSaveState').textContent='LIVE · SYNCED'}).subscribe(status=>{if(status==='SUBSCRIBED')$('sheetSaveState').textContent='LIVE · CONNECTED'})}

function queueSave(){let s=$('sheetSaveState');if(s)s.textContent='UNSAVED';clearTimeout(saveTimer);saveTimer=setTimeout(save,900)}
async function save(){if(!row)return;await api('/rest/v1/finance_workbooks?id=eq.'+row.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({snapshot:book,updated_at:new Date().toISOString(),updated_by:session().uid})});$('sheetSaveState').textContent='SAVED'}
function csvOut(){let s=sheet(),maxR=0,maxC=0;Object.keys(s.cells).forEach(k=>{let p=parse(k);maxR=Math.max(maxR,p.r);maxC=Math.max(maxC,p.c)});let out=[];for(let r=0;r<=maxR;r++){let row=[];for(let c=0;c<=maxC;c++){let v=String(val(r,c)??'');row.push(/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v)}out.push(row.join(','))}let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out.join('\n')],{type:'text/csv'}));a.download=s.name+'.csv';a.click()}
function csvIn(file){if(!file)return;let rd=new FileReader();rd.onload=()=>{snap();let lines=String(rd.result).split(/\r?\n/);lines.forEach((line,r)=>{let vals=[],cur='',q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'&&line[i+1]==='"'&&q){cur+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){vals.push(cur);cur=''}else cur+=ch}vals.push(cur);vals.forEach((v,c)=>cell(r,c).v=v)});renderAll();queueSave()};rd.readAsText(file)}
async function open(){let p=$('sheetPanel');p.innerHTML='<div class="ns-top"><div><small>RUN IT UP RECORDS</small><b>NATIVE FINANCE WORKBOOK</b></div><div><span id="sheetSaveState">LOADING</span><button id="csvIn">IMPORT CSV</button><button id="csvOut">EXPORT CSV</button><button id="saveNow">SAVE</button></div></div><div class="ns-toolbar"><div class="ns-tool-group"><span>TEXT STYLE</span><button data-f="b"><b>Bold</b></button><button data-f="i"><i>Italic</i></button><button data-f="u"><u>Underline</u></button></div><div class="ns-tool-group"><span>ALIGNMENT</span><button data-align="left">Align Left</button><button data-align="center">Align Center</button><button data-align="right">Align Right</button></div><div class="ns-tool-group"><span>COLORS</span><label>Text Color <input id="textColor" type="color" value="#111111"></label><label>Cell Color <input id="fillColor" type="color" value="#ffffff"></label></div><div class="ns-tool-group"><span>HISTORY</span><button id="undo">Undo</button><button id="redo">Redo</button></div></div><div class="ns-formula"><input id="nameBox" value="A1" title="Selected cell"><span>FORMULA / VALUE</span><input id="formulaInput" placeholder="Type a value or formula, e.g. =SUM(D4:D20)"></div><div id="nativeGrid" class="native-grid" tabindex="0"></div><div id="sheetTabs" class="sheet-tabs"></div><input id="csvFile" type="file" accept=".csv" hidden>';try{await load();renderAll();$('sheetSaveState').textContent='LIVE · CONNECTING';document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>format(b.dataset.f));document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>format('align',b.dataset.align));$('textColor').onchange=e=>format('color',e.target.value);$('fillColor').onchange=e=>format('bg',e.target.value);$('formulaInput').onkeydown=e=>{if(e.key==='Enter')commit(e.target.value)};$('nameBox').onkeydown=e=>{if(e.key==='Enter'){try{selected=parse(e.target.value);showSelection()}catch{}}};$('undo').onclick=undo;$('redo').onclick=redo;$('saveNow').onclick=save;$('csvOut').onclick=csvOut;$('csvIn').onclick=()=>$('csvFile').click();$('csvFile').onchange=e=>csvIn(e.target.files[0]);$('nativeGrid').focus()}catch(e){p.innerHTML='<div class="sheet-error">'+escape(e.message)+'</div>'}}
window.RIUSpreadsheet={open};
})();